### ISSUE TITLE
Lab 5 - Command does not limit ingress

### ISSUE THREAD

**Issue by bhpratt** [IBM/container-service-getting-started-wt#36]
This command does not correctly limit ingress: `kubectl annotate ns advanced-policy-demo "net.beta.kubernetes.io/network-policy={\"ingress\":{\"isolation\":\"DefaultDeny\"}}"`

When we verify the YAML later in the lab, ingress is still set to allow:

```
- apiVersion: v1
  kind: profile
  metadata:
    name: k8s_ns.advanced-policy-demo
    tags:
    - k8s_ns.advanced-policy-demo
  spec:
    egress:
    - action: allow
      destination: {}
      source: {}
    ingress:
    - action: allow
      destination: {}
      source: {}
```
